### ISSUE TITLE
Crashing with decoder does not support parameter changes

### ISSUE THREAD

**Issue by shilpim** [matthewn4444/VPlayer_lib#6]
ffmpeg: This decoder does not support parameter changes, but PARAM_CHANGE side data was sent

java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@537a9bd0 does not exist
                                                                at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7640)
                                                                at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7631)
                                                                at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:854)
                                                                at android.os.BinderProxy.sendDeathNotice(Binder.java:449)
                                                                at dalvik.system.NativeStart.run(Native Method)

**Comment by matthewn4444** [comment]
Can you provide an example to reproduce this issue?
